name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install --cask archiver
      - name: Install Theos
        uses: Randomblock1/theos-action@v1.3
      - name: Make ChOma
        run: |
          git clone https://github.com/opa334/ChOma.git
      - name: Make TrollStore
        run: |
          make 
